### ISSUE TITLE
Support for wildcards

### ISSUE THREAD

**Issue by nmn** [benbria/aliasify#12]
Browserify's official way to support local modules is to put them in the node_modules folder and add an exception in the .gitignore

A way to do wildcard aliases would be great:
```
'app/*' : './local_modules/*'
```

**Comment by revolunet** [comment]
Did you solve the problem ?

**Comment by nmn** [comment]
Nope. Still using the .gitignore solution that barely works.

**Comment by jwalton** [comment]
I am 99% sure you can already do this.  If you do:

    'app' : './local_modules'

then when you:

    require('app/foo');

this should get rewritten to point to the local_modules version.

**Comment by pmowrer** [comment]
@jwalton I can confirm that your proposed solution works. Thanks!
