### ISSUE TITLE
Issues when using npm shrinkwrap or npm ls because of node-falafel

### ISSUE THREAD

**Issue by gionkunz** [benbria/aliasify#15]
Hi there

There is a long running issue with node-falafel that uses esprima as a bundledDependencies https://github.com/substack/node-falafel/blob/master/package.json#L25 and therefore causing "ERR! extraneous: esprima@1.1.0-dev".

There are several issues already open and even pull requests:
https://github.com/substack/node-falafel/issues/30
https://github.com/substack/node-falafel/issues/28
https://github.com/substack/node-falafel/pull/29

I don't understand why this doesn't get fixed. I respect substack and understand he has a lot on his plate but this issue is going on for too long and it'd just be a matter of accepting a PR.

As a workaround I could see the following options:

- Someone creates a fork of node-falafel, fixes the issue and publish to npm so we can all switch our libraries to use the new dependency
- Someone close to substack physically forces him to accept the pull request  https://github.com/substack/node-falafel/pull/29 :smile: 
- If you don't mind switching to node-burrito this is probably also an alternative

What do you think?

Cheers
Gion

**Comment by scamden** [comment]
@gionkunz why does this go to browserify-transform-tools? bundling the dep and not declaring it in your package.json is breaking shrinkwrap for anyone that uses falafel

**Comment by jwalton** [comment]
Sounds like this is fixed in the latest falafel?  I've upgraded browserify-transform-tools to use falafel@1.0.1, and updated aliasify to use the latest browserify-transform-tools.  Let me know if this is still a problem.

**Comment by gionkunz** [comment]
Coolio!
