### ISSUE TITLE
Alias and dot notation

### ISSUE THREAD

**Issue by gobwas** [benbria/aliasify#29]
Hello!

Is it possible to do something like this:

```js
var cat = require("animals").cat;
```
->

```js
var cat = require("../shim/to/animals.js").dog;
```

?

Thanks!

**Comment by jwalton** [comment]
Probably the easiest way to do this would be to set up an alias from 'animals' to 'shim/to/animalConverter.js', which would look something like:

    var animals = require('./animals.js');
    module.exports = {
        dog: animals.cat
    };

**Comment by gobwas** [comment]
Hm. I've used the absolutely easiest way to use a `browserify-replace` transform :laughing: 
Thank you for your advice! :beers:
