### ISSUE TITLE
Is there support for bower installations with aliasify?

### ISSUE THREAD

**Issue by joseph-norman** [benbria/aliasify#30]
When using the following configuration:

```
exports.aliasConfig = {
  aliases: {
    'modernizr': {
      'relative': '<bower_directory>/modernizr/modernizr.js'
    },
    'lodash': {
      'relative': '<node_modules_directory>/lodash/index.js'
    }
  },
  configDir: 'dist',
  verbose: true
}
```

(Obviously omitting the directories above with placeholders). The `node_modules/*` aliases work fine, but the bower aliases do not. I'm using the CommonJS requires for bower in my source code i.e `require('modernizr`);`.

If there's no support, would you be open to a pull request to fix it?

**Comment by jwalton** [comment]
This ought to work.  Aliasify doesn't know anything about what kind of file you're aliasing; there's no special case for node_modules or anything.
